export interface SeedIdea2 {
  title: string;
  category: string;
  format: string;
  done?: boolean;
}

const DONE_TITLES = new Set([
  "Şeytanın Avukatı — başarı, kibir ve içsel çöküş",
  "Everything Everywhere All at Once — çoklu evren ve anlam",
  "Maskara ömrü neden 3 aydan az?",
  "Sarı Göz Farı Teorisi",
  "Backrooms",
  "Disclosure Day",
  "Oak Caddesi'nin Sonu",
  "Obsession — One Wish Willow",
  "Bare Nails",
  "Kozmik Takvim",
  "Lebdeğmez",
]);

function mk(category: string, titles: string[]): SeedIdea2[] {
  return titles.map((title) => ({
    title,
    category,
    format: "Video",
    done: DONE_TITLES.has(title),
  }));
}

export const CONTENT_IDEA_SEED_2: SeedIdea2[] = [
  ...mk("Film - Psikolojik Alt Metin", [
    "Şeytanın Avukatı — başarı, kibir ve içsel çöküş",
    "Memento — hafıza olmadan kimlik var mı?",
    "Black Swan — mükemmeliyetçilik bir yok oluş biçimidir",
    "Mulholland Drive — bastırılan arzunun rüya dili",
    "American Psycho — kimliksizliğin maskesi olarak şiddet",
    "Whiplash — büyüklük mü yoksa kendine işkence mi?",
    "Donnie Darko — kahramanlık, kader ve kurban edilme",
    "The Truman Show — konfor alanı bir hapishane olduğunda",
    "Eternal Sunshine — acıyı silmek bizi yoksullaştırır mı?",
    "Shutter Island — kendinden kaçışın imkânsızlığı",
    "Requiem for a Dream — bağımlılığın dört ritmi",
    "Taxi Driver — yalnızlığın doğurduğu mesih kompleksi",
    "The Machinist — suçluluğun bedeni yiyip bitirmesi",
    "Prisoners — adalet ile intikam arasındaki ince çizgi",
    "Nightcrawler — empatisizlik bir kariyer avantajı mı?",
    "There Will Be Blood — hırsın insanı tek başına bırakması",
    "The Lighthouse — izolasyon ve akıldan çıkış",
    "Enemy — kendi ikizinle yüzleşmek",
    "Oldboy — intikamın kendini tüketmesi",
    "Joker — toplumun ürettiği canavar",
    "Birdman — ego, alkış ve geçersizlik korkusu",
    "A Clockwork Orange — özgür irade alınınca ahlak kalır mı?",
    "The Master — lidere duyulan açlık ve ruhsal boşluk",
    "Synecdoche New York — hayatı kontrol etme yanılsaması",
    "Perfect Blue — kimlik ile imaj arasındaki çöküş",
    "Parasite — sınıf, koku ve görünmezlik felsefesi",
    "Burning — belirsizlik ve bastırılmış öfke",
    "I'm Thinking of Ending Things — geriye dönük benlik yanılsaması",
    "The Talented Mr. Ripley — sahte kimliğin psikolojisi",
    "Shame — bastırılmış utancın bedeni ele geçirmesi",
    "Melancholia — depresyon ve kozmik kabul",
    "Dancer in the Dark — illüzyonun gerçeği aşması",
    "American History X — öfkenin kökeni ve dönüşümü",
    "Seven — günahların aynasında tanrısal kibir",
    "No Country for Old Men — kaçınılmaz kaderin sessizliği",
    "Incendies — nesiller arası travmanın döngüsü",
    "Babel — iletişimsizliğin yarattığı trajedi",
    "Magnolia — tesadüf mü, kader mi?",
    "The Tree of Life — varoluşun annesiz kalması",
    "Amadeus — kıskançlık, deha ve Salieri sendromu",
  ]),

  ...mk("Film - Okült Sembolizm", [
    "The Devil's Advocate — Milton'ın gerçek kimliği ve isim sembolizmi",
    "Hereditary — kadim kült ve kontrol illüzyonu",
    "Midsommar — ışıkta saklanan karanlık ritüel",
    "The Holy Mountain — simya ve aydınlanma yolculuğu",
    "Pi — Kabala, sayılar ve takıntının laneti",
    "The Ninth Gate — kitap, kapı ve şeytani bilgi",
    "Eyes Wide Shut — gizli ayinler ve maske sembolizmi",
    "Annihilation — dönüşüm ve benliğin erimesi",
    "The Witch — günah, izolasyon ve baştan çıkma",
    "Suspiria — cadılık ve bedenin dili",
    "Mandy — psychedelic intikam ve kült estetiği",
    "Stalker — Bölge, arzu odası ve inanç",
    "The Fountain — ölüm, ağaç ve sonsuz dönüş",
    "Jacob's Ladder — ölüm anının arınma yolculuğu",
    "The Green Knight — onur sınavı ve ölümle yüzleşme",
    "El Topo — kahramanın simyasal arınması",
    "Coraline — eşik, ayna ve öteki dünya",
    "Spirited Away — isim, kimlik ve ruhsal geçiş",
    "Princess Mononoke — doğa ruhları ve denge",
    "Under the Skin — bedenin yabancılığı ve empati deneyi",
    "Black Mirror: Bandersnatch — özgür irade bir yanılsama mı?",
    "The Wicker Man — eski tanrılar ve kurban antropolojisi",
    "Pan's Labyrinth — hayal mi, gerçek mi?",
    "Rosemary's Baby — güven, ihanet ve bedenin mülkiyeti",
    "The Others — bilinmezliğin yarattığı gerçeklik",
    "The Ritual — ormanda gizlenen arkaik korku",
    "Lynch sinemasında bilinçdışı harita",
    "Kubrick'in filmleri neden bitmez?",
    "Solaris — bilinçdışının dışsallaşması",
    "2001: A Space Odyssey — monolit, evrim ve kibir",
    "The Shining — mekân, zaman ve travmanın döngüsü",
    "Full Metal Jacket — kimlik silme ve kolektif şiddet",
    "A.I. — bilinç bir programlanma biçimi midir?",
    "Blade Runner 2049 — anı gerçekliğin kanıtı mı?",
    "Everything Everywhere All at Once — çoklu evren ve anlam",
    "Mother! — yaratıcının tüketilen bedeni",
    "Doctor Sleep — travmanın kuşaklar arası aktarımı",
    "Ari Aster filmlerinde yas ve kültik yeniden doğuş",
    "2001'de Nietzsche — üstinsan ve monolit",
    "Hereditary'de Paimon sembolizmi",
  ]),

  ...mk("Kitap & Edebiyat", [
    "Suç ve Ceza — vicdan bir hapishanedir",
    "Karamazov Kardeşler — Büyük Engizisyoncu ve özgürlük korkusu",
    "Yeraltından Notlar — modern insanın felci",
    "1984 — dil düşünceyi nasıl öldürür",
    "Cesur Yeni Dünya — mutlulukla köleleştirmek",
    "Dorian Gray — narsisizmin portresi",
    "Frankenstein — yaratıcının terk ettiği yaratık",
    "Drakula — bastırılmış Viktoryen arzu",
    "Faust — bilgi uğruna ruhu satmak",
    "Moby Dick — takıntı bir kişiyi nasıl yutar",
    "Dönüşüm (Kafka) — yabancılaşmanın bedenleşmesi",
    "Dava (Kafka) — anlamsız sistem karşısında birey",
    "Şato — ulaşılamayan otorite",
    "Sefiller — adalet, merhamet ve dönüşüm",
    "Don Kişot — yanılsama ile gerçeğin savaşı",
    "Yüzyıllık Yalnızlık — döngüsel zaman ve kader",
    "Steppenwolf — çoklu benlik ve burjuva sıkışması",
    "Demian — Abraxas ve içsel rehber",
    "Siddhartha — bilgiden deneyime giden yol",
    "Körlük (Saramago) — uygarlığın kırılganlığı",
    "Fareler ve İnsanlar — rüyaların kırılganlığı",
    "Çavdar Tarlasında Çocuklar — sahtelik korkusu",
    "Otomatik Portakal — koşullanma ve ahlak",
    "Solaris — temas edilemeyen öteki",
    "Ubik (P.K. Dick) — gerçeklik katmanları ve ölüm",
    "Valis (P.K. Dick) — tanrısal bilgi ve delilik sınırı",
    "Dune — mesih mitinin tehlikeli yanı",
    "Neuromancer — dijital bilinç ve beden yitimi",
    "Ender's Game — çocukları silahlaştıran sistem",
    "The Road — anlamsız dünyada babalık ve anlam",
    "Blood Meridian — şiddetin kozmik boyutu",
    "Borges'te labirent ve sonsuzluk",
    "Poe'nun hikâyelerinde bilinçdışı haritası",
    "Lovecraft'ın kozmik korkusu: insanın önemsizliği",
    "Bulgakov'un Usta ve Margarita'sında şeytan figürü",
    "Umberto Eco — semiyotik ve anlam inşası",
    "Kafka'nın mektupları — dâhinin iç savaşı",
    "Camus'nün Yabancısı — anlamsızlıkla barış",
    "Sartre'ın Bulantısı — varoluş özden önce gelir",
    "Hesse'nin Narziss ve Goldmund'u — iki hayat, iki hakikat",
  ]),

  ...mk("Bilim Felsefesi", [
    "Gözlemci olmadan gerçeklik var mı? — kuantum ölçüm sorunu",
    "Zaman gerçek mi yoksa zihnin kurgusu mu?",
    "Özgür irade bir yanılsama mı? — Libet deneyleri",
    "Simülasyon argümanı — içinde mi yaşıyoruz?",
    "Çin Odası — makine gerçekten anlar mı? (Searle)",
    "Schrödinger'in kedisi — gerçeklik kararsızlığı",
    "Entropi — neden zaman hep ileri akar?",
    "Gödel'in eksiklik teoremi — matematik tamamlanamaz",
    "Çift yarık deneyi — bilinç maddeyi etkiler mi?",
    "Ockham'ın usturası gerçekten doğruyu mu verir?",
    "Theseus'un gemisi — kimlik değişimle kalır mı?",
    "Kara kuğu — öngörülemezliğin felsefesi (Taleb)",
    "Antropik ilke — evren bizim için mi ayarlı?",
    "Yanlışlanabilirlik — bilim neyi bilim yapar? (Popper)",
    "Paradigma kayması — bilim nasıl devrim yapar? (Kuhn)",
    "Maxwell'in cini — bilgi ve termodinamik",
    "Bilinç zor problemi — qualia neden var? (Chalmers)",
    "Filozofik zombi — içsel deneyim olmadan davranış",
    "Mary'nin odası — bilgi her şey midir? (Jackson)",
    "Boltzmann beyni — evren bir rastlantı mı?",
    "Heisenberg belirsizliği — bilinemezliğin sınırı",
    "Çoklu evren — her seçim yeni bir dünya mı? (Everett)",
    "Holografik evren — gerçeklik iki boyutlu mu?",
    "Fermi paradoksu — büyük sessizlik neyi anlatır?",
    "Kaos teorisi — kelebek etkisi ve determinizm",
    "Emergent properties — bütün parçaların toplamından fazladır",
    "Bilincin matematiksel temeli mümkün mü? (Tononi)",
    "İndirgemecilik neden her şeyi açıklamaz?",
    "Panpsişizm — her şey bilinçli midir?",
    "Evrimsel epistemoloji — doğru düşünceye seçilim mi yaptı?",
    "Nöral determinizm — beyin bir yargıç mı mahkum mu?",
    "Plasebo etkisi bize inanç ve biyoloji hakkında ne söyler?",
    "Ölçüm problemi — gözlemleyen kim?",
    "Zamanın oku — neden geleceği hatırlayamıyoruz?",
    "Koyu madde — görünmeyenin ağırlığı",
    "Büyük çöküş teorisi — evren nereye gidiyor?",
    "Geri bildirim döngüleri ve karmaşıklık",
    "Teleoloji — evrenin bir amacı var mı?",
    "İnformasyon teorisi ve gerçeklik ilişkisi",
    "Mahkûm ikilemi — işbirliği neden bu kadar zordur?",
  ]),

  ...mk("Psikoloji Kavramları", [
    "Gölge arketipi — bastırdığın seni yönetir (Jung)",
    "Ahlaki lisans — iyilik yapınca kendine izin vermek",
    "Bilişsel çelişki — yalanlarımıza neden inanırız (Festinger)",
    "Stockholm sendromu — kaptana bağlanmak",
    "Dunning-Kruger — bilgisizliğin verdiği özgüven",
    "Doğrulama yanlılığı — sadece görmek istediğimiz",
    "Persona ile gerçek benlik arasındaki uçurum (Jung)",
    "Yansıtma — başkasında nefret ettiğimiz şey",
    "Öğrenilmiş çaresizlik — neden vazgeçeriz (Seligman)",
    "Sapkın narsisizmin sinemada portresi",
    "Travma ve tekrar — aynı acıyı seçmek",
    "Karanlık üçlü — narsisizm, makyavelizm, psikopati",
    "Halo etkisi — güzellik neden güveni satın alır",
    "Sürü psikolojisi — kalabalıkta vicdan kaybolur",
    "Lucifer etkisi — iyi insan nasıl kötülük yapar? (Zimbardo)",
    "Milgram deneyi — emir altında ahlak çözülür mü?",
    "Bystander etkisi — neden kimse yardım etmez?",
    "İçsel çocuk — kararlarımızı kim veriyor?",
    "Varoluşsal kaygı — özgürlüğün ağırlığı (Frankl)",
    "İmposter sendromu — başarıya inanamamak",
    "Bağlanma stilleri — ilişki kalıplarımızın kökeni (Bowlby)",
    "Savunma mekanizmaları — zihnin kalkanları (Freud)",
    "Akış hali — benliğin kaybolması (Csikszentmihalyi)",
    "Bireyleşme — gerçek kendine dönüş (Jung)",
    "Dissosiyasyon — gerçeklikten kopuşun psikolojisi",
    "Travma bağı neden bu kadar güçlüdür?",
    "Kompleks PTSD ve filmlerdeki yansıması",
    "Algı yönetimi — biz mi seçiyoruz, çevre mi?",
    "Yanlı hafıza — geçmişi neden yeniden yazarız?",
    "Ego tükenmesi — irade sınırlı bir kaynak mıdır? (Baumeister)",
    "Sosyal uyum baskısı — kimsenin sormadığı soru (Asch)",
    "Utanç — kültürel bir silah olarak",
    "Güç dinamikleri ilişkileri nasıl şekillendirir?",
    "Kendini sabote etmek neden bu kadar yaygın?",
    "Psikolojik güvenlik — yaratıcılığın tek koşulu",
    "Salieri sendromu — başkasının dehası karşısında çöküş",
    "Kimlik füzyonu — role o kadar gömülmek ki kaybolmak",
    "Dopamin döngüsü — tatmin değil, açlık açar",
    "Kıskançlık ile hayranlığın iç içe geçmesi",
    "Öfke bastırmanın bedeli — sinema ve psikoloji",
  ]),

  ...mk("Kadim Bilgelik & Mitoloji", [
    "Hermes Trismegistos — \"yukarısı nasılsa aşağısı öyle\"",
    "Ouroboros — kendini yiyen yılan ve sonsuz döngü",
    "Prometheus — bilgiyi çalmanın bedeli",
    "İkarus — yükselişin kibirle düşüşü",
    "Sisifos — anlamsız tekrarda anlam bulmak (Camus)",
    "Pandora'nın kutusu — umut neden en sona kaldı?",
    "Narkissos — kendine âşık olmanın laneti",
    "Mısır'da ikinci ölüm — benliğin gerçek çözülüşü",
    "Tibet Ölüler Kitabı — ara durum ve bilinç",
    "Platon'un mağarası — gölgeleri gerçek sanmak",
    "Simya — kurşunu altına çevirmenin içsel anlamı",
    "Kabala — Hayat Ağacı ve bilinç katmanları",
    "Yin-Yang — karşıtlıkların birliği",
    "Gnostisizm — uyanış ve sahte tanrı (Demiurge)",
    "Tao — yapmayarak yapmak (wu wei)",
    "Maya — dünya bir yanılsama perdesidir",
    "Karma — neden-sonuç bir adalet sistemi mi?",
    "Şamanizm — alt dünya yolculuğu ve dönüşüm",
    "Eleusis gizemleri — ölüm ve yeniden doğuş ritüeli",
    "Orpheus — sevgiliyi geri getirme ve geriye bakma",
    "Kronos — zamanın kendi çocuklarını yutması",
    "Janus — geçmiş ve geleceğe bakan iki yüz",
    "Norse Ragnarök — sonun yeni başlangıç olması",
    "Kahramanın yolculuğu — Campbell'ın tek miti",
    "Osiris'in parçalanması ve yeniden birleşmesi",
    "Hermetik yedi ilke — düşünce gerçeği yaratır",
    "Zerdüştlük — iyilik ve kötülüğün kozmik savaşı",
    "Budist bodhisattva — kurtuluşu ertelemek",
    "Sfenks'in sorusu — insanlığın tanımı",
    "Labirent arketipi — kaybolmak ve bulmak",
    "Tarot kartlarının psikolojik haritası",
    "Zaman tanrıları — neden her kültürde var?",
    "Kaos ve kozmos — düzenin kırılgan kökeni",
    "Mitolojide trickster figürü — düzeni bozan kahraman",
    "Gece yolculuğu arketipi — bilinçdışının derinliğine iniş",
    "Caduceus — tıbbın gizli simyası",
    "Ateş hırsızlığı — her mitolojinin ortak motifi",
    "Kelt mitinde öteki dünya eşikleri",
    "Hindu trimurti — yaratma, koruma, yıkım döngüsü",
    "Rünler — dilden önce gelen işaretler",
  ]),

  ...mk("Bilinç, Zaman & Gerçeklik", [
    "Déjà vu nedir — hafıza bir hata mı yapıyor?",
    "Rüyalar neden anlatı kurar?",
    "Lucid rüya — bilinç uykuda uyanırsa",
    "Mandela etkisi — kolektif yanlış hatırlama",
    "Zamanın geçişi neden yaşla hızlanır?",
    "Şimdi diye bir an gerçekten var mı?",
    "Ego ölümü — ben çözülünce ne kalır?",
    "Bilinç beynin mi, beyin bilincin mi içinde?",
    "Kör nokta — beynin uydurduğu gerçeklik",
    "Renk gerçekten var mı yoksa beyinde mi?",
    "Ayna testi — kendini tanıma ne demek?",
    "İç ses — kiminle konuşuyoruz?",
    "Hafıza her hatırladığımızda değişir mi? (Damasio)",
    "Acı bir yanılsama olabilir mi?",
    "Zaman algısı korku anında neden yavaşlar?",
    "Bilinçaltı kararlarımızı önceden mi verir? (Libet)",
    "Beyin ölümünde son saniyeler ne yaşar?",
    "Sezgi — bilmeden bilmek mümkün mü?",
    "Boşluk korkusu — neden sessizlikten kaçarız?",
    "Kendilik bir illüzyon mu? (Budist görüş)",
    "Sonsuzluk kavramını zihin neden alamaz?",
    "Hiçlik neden bir şeyden çok bir şeydir?",
    "Gerçeklik uzlaşımsal bir kurgu mu?",
    "Düşünceler nereden gelir?",
    "Uyku felci — bilinç sınırındaki yaratıklar",
    "Sinestezi — duyuların karışması bize ne öğretir?",
    "Beyin bütünlük için hikâye uydurur mu?",
    "Geçmiş gerçekten geçti mi?",
    "Bilinç sadece insana özgü müdür?",
    "Ahtapot bilinçli midir? — bilinç tanımı sorunu",
    "Empati bir yanılsama mı, yoksa evrimsel mi?",
    "Bilinç akışı — düşüncenin geometrisi",
    "Dikkat neden bu kadar sınırlı ve değerli?",
    "Paralel bilinç — çoklu evren ve benlik",
    "Sonsuz olasılık anlam öldürür mü? (Sartre)",
    "Zaman körlüğü — şimdiye takılıp kalmak",
    "Birleşik varoluş hissi nedir?",
    "Yanılsamalı kendilik — Zen perspektifi",
    "İnsanın zaman kavramı diğer türlerden farklı mı?",
    "Ölüm farkındalığı bilinci nasıl değiştirir? (Heidegger)",
  ]),

  ...mk("İnsan Doğası & Karanlık Temalar", [
    "İnsan neden acımasızlığa kapılır?",
    "Kötülüğün sıradanlığı — Arendt'in tezi",
    "Neden kendimize en çok yalan söyleriz?",
    "Güç insanı neden değiştirir?",
    "Yalnızlık neden hem korkutur hem çeker?",
    "İntikam neden tatmin etmez?",
    "Pişmanlık geçmişi değiştiremezken neden var?",
    "Kıskançlık — sevginin gölgesi mi?",
    "Utanç ile suçluluk arasındaki fark",
    "İnsan neden kendi çıkarına karşı davranır?",
    "Konformizm — neden sürüye uyarız? (Asch)",
    "Kahraman ile katil aynı kökten mi gelir?",
    "Maske takmak bizi kim yapar?",
    "Affetmek zayıflık mı güç mü?",
    "İnsan ölümü neden bilince çıkaramaz?",
    "Anlam arayışı bir kaçış mı? (Frankl)",
    "Konfor neden ruhu çürütür?",
    "Başarı neden mutlu etmez?",
    "İçsel boşluğu neyle doldururuz?",
    "Sevgi bir seçim mi yoksa kimyasal mı?",
    "Nefret neden bağımlılık yapar?",
    "İnsan neden kendi kafesini kurar?",
    "Özgürlük neden insanı korkutur? (Fromm)",
    "İyilik yapmak neden bazen acı verir?",
    "Yabancılaşma — modern insanın kaçınılmaz kaderi mi?",
    "Yaratıcılık ile acı arasındaki ilişki",
    "İnsan anlamsızlıkla nasıl barışabilir?",
    "Neden bazı insanlar hayatta acıyı tercih eder?",
    "Kibir — sessiz hayranlığın en tehlikeli biçimi",
    "Başarısızlık korkusu mu, başarı korkusu mu daha yaygın?",
    "İnsan neden tanınmak için her şeyi yapar?",
    "Varoluşsal yalnızlık — kimseyle tam paylaşılamayan",
    "Bencillik evrimsel mi yoksa kültürel mi?",
    "Neden bazı travmalar bizi güçlendirir?",
    "Yas tutmak neden bu kadar bireysel?",
    "Hayal kırıklığı bizi kim yapar?",
    "İnsan doğası iyi mi kötü mü? — felsefe tarihi boyunca",
    "Suçluluk duygusu sağlıklı mı yoksa zehirli mi?",
    "Bağımlılık bir tercih mi yoksa hastalık mı?",
    "İnsan neden kendini cezalandırır?",
  ]),

  ...mk("Teknoloji × Felsefe", [
    "AI bize kim olduğumuzu söyleyebilir mi?",
    "GPT Mağara Alegorisi'ni anlasaydı",
    "Elon Musk'un zihin modeli — Stoacılık mı kibir mi?",
    "Apple'ın tasarım felsefesi aslında Wabi-sabi'dir",
    "Kuantum bilgisayar gerçekten bilinci değiştirir mi?",
    "Teknoloji şirketleri bize Huxley'i yaşatıyor",
    "Metaverse'in simülasyon argümanıyla bağlantısı",
    "ChatGPT bizi gerçekten anlıyor mu? — Turing testi ötesi",
    "Algoritmalar özgür iradeyi öldürüyor mu?",
    "Sosyal medya bir Panopticon mudur? (Foucault)",
    "NFT ve değer felsefesi — bir şey neden değerlidir?",
    "Transhumanizm — insanlığı aşmak ne demek?",
    "Beyin-bilgisayar arayüzü ve kimlik sorunu",
    "Yapay zeka sanat üretirse sanatçı kim?",
    "Deep fake gerçeği öldürür mü?",
    "Gözetleme kapitalizmi — dikkat ekonomisinin bedeli (Zuboff)",
    "Filter bubble — algoritmalar düşünce hapishanesi mi?",
    "Otomasyonun yarattığı varoluşsal kriz",
    "Robot etiği — makinelerin ahlakı olabilir mi?",
    "CRISPR — insanı tasarlamak etik mi?",
    "Uzay kolonizasyonu — kaçış mı, yayılma mı?",
    "Singularity — yapay zekanın insanı aşacağı an",
    "Open source ve bilginin demokratikleşmesi",
    "Steve Jobs'un Zen felsefesi ürünleri nasıl şekillendirdi?",
    "Google'ın \"Don't Be Evil\" ilkesi neden yetmedi?",
    "Teknoloji bağımlılığı ile uyuşturucu bağımlılığı aynı mı?",
    "Yapay zeka önyargısı — kodun içindeki insanlık hatası",
    "Dijital kimlik gerçek kimlik midir?",
    "Ekolojik çöküş ve teknolojik kurtuluş yanılsaması",
    "İnternet hafızası — dijital ölümsüzlük mümkün mü?",
  ]),

  ...mk("Bilim Kurgu & Distopya", [
    "Distopya edebiyatı neden bugün bu kadar popüler?",
    "Blade Runner evreninde insan olmak ne demek?",
    "Dune'un mesih uyarısı — kahraman tehlikelidir",
    "Dark (Netflix) — zaman paradoksu ve determinizm",
    "Westworld — bilinç nasıl uyanır?",
    "Black Mirror en çok hangi felsefi korkuyu gösteriyor?",
    "Foundation — tarih tekrar eder mi? (Asimov)",
    "Arrival — dil düşünceyi ve zamanı şekillendirir mi?",
    "Ex Machina — yapay zekayı seven insanın trajedisi",
    "Her (film) — sanal sevginin gerçekliği",
    "Children of Men — umut olmadan yaşamak",
    "Wall-E — tüketim uygarlığının sonu",
    "Interstellar'da zaman ve sevginin evrenseli",
    "Philip K. Dick'in en karanlık kehaneti hangisi?",
    "Bilim kurgu ütopya mı distopya mı — fark kapandı mı?",
  ]),

  ...mk("Moda/Güzellik/Trend", [
    "Hafızanı güçlendirmek istiyorsan hangi kitapları oku",
    "Kaygılıysan hangi felsefeyi öğren",
    "Yaratıcı tıkanma yaşıyorsan ne yap",
    "Cilt tipine göre nemlendirici nasıl seçilir",
    "Kaşmir gerçek mi sentetik mi anla",
    "Ten rengine göre hangi lipstick tonu seçilmeli",
    "Aksesuar seçerken minimalizm mi maksimalizm mi sana uygun",
    "Cildi güneşten koruyan gerçek bileşenler neler",
    "Kalite işareti olan etiketleri tanı",
    "Parfüm notaları nasıl okunur",
    "Kumaş yıkama etiketini doğru okumayı bil",
    "\"Old money\" estetiği gerçekten eski parayı mı temsil ediyor?",
    "Quiet luxury bir trend mi yoksa pazarlama hilesi mi?",
    "Clean girl estetiği neden bu kadar pahalı?",
    "Capsule wardrobe gerçekten para biriktiriyor mu?",
    "Dupe kültürü — aynısını ucuza almak etik mi?",
    "Skin cycling gerçekten işe yarıyor mu yoksa TikTok trendi mi?",
    "Slugging yöntemi cildi mi besliyor yoksa tıkıyor mu?",
    "\"Clean beauty\" etiketi bilimsel bir şey mi yoksa pazarlama mı?",
    "Retinol vs bakuchiol — hangisi gerçekten işe yarıyor?",
    "\"Buy less, buy better\" mottosu gerçekçi mi?",
    "Dermaplaning gerçekten peeling mi yapıyor?",
    "Maskara ömrü neden 3 aydan az?",
    "\"Hormonal cilt\" gerçek mi yoksa pazarlama terimi mi?",
    "Neden bazı parfümler sende farklı, arkadaşında farklı kokuyor?",
    "Vintage moda neden yeniden lükse döndü?",
    "Mikroplastik cilt ürünlerinde nereden geliyor?",
    "Cilt bakım rutini gerçekten 10 adım olmalı mı?",
    "\"Anti-aging\" kelimesi bilimsel olarak ne anlama geliyor?",
    "Neden bazı markalar aynı ürünü farklı ülkelerde farklı formülle satıyor?",
  ]),

  ...mk("Teori + Bilim Serisi", [
    "Sarı Göz Farı Teorisi",
    "Kırmızı ruj teorisi — çekicilik algısı, evrimsel biyoloji",
    "5-4-3-2-1 kaygı tekniği — nörobilimsel temeli var",
    "Soğuk duş teorisi — kısmen bilimsel",
    "Güç pozu teorisi — Amy Cuddy araştırması, sonradan tartışmalı bulundu",
    "444 melek sayıları — confirmation bias",
    "Ayna manifestasyonu — plasebo ötesi kanıt yok",
    "Kırmızı iplik koruma teorisi — kültürel inanç, bilimsel temel yok",
    "69 saniye düşünme kuralı — hiçbir çalışma desteklemiyor",
    "Ay döngüsü ve duygu durumu teorisi",
    "Genel renk terapisi — bazıları kanıtlı (sarı), bazıları değil",
  ]),

  ...mk("Ek Konular (Üretim Takibi)", [
    "Backrooms",
    "Disclosure Day",
    "Oak Caddesi'nin Sonu",
    "Peter Pan'in Asıl Hikâyesi",
    "Alice Harikalar Diyarının Asıl Hikâyesi",
    "Funny Games",
    "Alan Turing'in Sonu",
    "Obsession — One Wish Willow",
    "Bare Nails",
    "Renkli Saç",
    "Project Hail Mary",
    "Kozmik Takvim",
    "Lebdeğmez",
    "Abonelik Endüstrisi",
    "Güneş Kremi Etiketleri (PA/SPF)",
    "İskenderiye Kütüphanesi ve Dua Lipa",
  ]),
];
